### ISSUE TITLE
Add RSS or Atom feed for blog

### ISSUE THREAD

**Issue by weewoo22** [h33p/django-blog#1]
I'm sure there's a couple good Django addons for this on https://djangopackages.org/

**Comment by h33p** [comment]
That's a good idea, I've wanted to add RSS for a long time, but never got around it. Hopefully I can actually sit down to it very soon.

**Comment by h33p** [comment]
At long last, this has been resolved in https://github.com/h33p/django-blog/commit/c280c27e44fa509191de820ba9cda51357be4255
